import React from 'react';
import { Tag } from 'antd';
import {
    CloudUploadOutlined,
    RobotOutlined,
    TagsOutlined,
    EditOutlined,
    DatabaseOutlined,
    ApiOutlined
} from '@ant-design/icons';

const techStack = [
    { name: 'React.js', color: '#61dafb' },
    { name: 'Node.js', color: '#68a063' },
    { name: 'MongoDB', color: '#4db33d' },
    { name: 'GridFS', color: '#f0a500' },
    { name: 'Gemini Vision API', color: '#8e44ad' },
    { name: 'Ant Design', color: '#1890ff' },
];

const steps = [
    {
        icon: <CloudUploadOutlined />,
        title: 'Upload Images',
        desc: 'Drag and drop or click to upload JPEG/PNG images to the gallery.',
    },
    {
        icon: <RobotOutlined />,
        title: 'AI Analysis',
        desc: 'Google Gemini Vision API processes your image and extracts visual understanding.',
    },
    {
        icon: <TagsOutlined />,
        title: 'Metadata & Tags',
        desc: 'Auto-generated descriptive caption and smart keyword tags are added to each image.',
    },
    {
        icon: <DatabaseOutlined />,
        title: 'Stored Securely',
        desc: 'Images are stored via MongoDB GridFS, and metadata is persisted for quick retrieval.',
    },
    {
        icon: <EditOutlined />,
        title: 'Edit Captions',
        desc: 'Refine or rewrite AI-generated captions to perfectly match your intent.',
    },
];

const AboutPage = () => {
    return (
        <div className="about-page">
            {/* Intro */}
            <section className="about-intro">
                <h1 className="about-headline">About AIGALLARYIMAGE</h1>
                <p className="about-description">
                    AIGALLARYIMAGE is a demo-ready AI-powered image understanding application.
                    Upload any image and instantly receive an intelligent caption and relevant tags,
                    generated by Google's Gemini Vision API. It's designed to showcase the power
                    of AI in visual content understanding.
                </p>
            </section>

            {/* How It Works */}
            <section className="about-section">
                <h2 className="about-section-title">
                    <ApiOutlined /> How It Works
                </h2>
                <div className="about-steps">
                    {steps.map((step, i) => (
                        <div key={i} className="about-step-card">
                            <div className="about-step-number">{i + 1}</div>
                            <div className="about-step-icon">{step.icon}</div>
                            <h3>{step.title}</h3>
                            <p>{step.desc}</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* Tech Stack */}
            <section className="about-section">
                <h2 className="about-section-title">
                    <DatabaseOutlined /> Tech Stack
                </h2>
                <div className="tech-stack-grid">
                    {techStack.map((tech) => (
                        <Tag
                            key={tech.name}
                            color={tech.color}
                            className="tech-tag"
                        >
                            {tech.name}
                        </Tag>
                    ))}
                </div>
            </section>
        </div>
    );
};

export default AboutPage;
